baseURL = 'https://blog.devhou.se/'
languageCode = 'ja'
title = 'devhou.se'
theme = 'devhouse-theme'
copyright = '© 2025 devhou.se'

[taxonomies]
  author = 'authors'

[outputs]
  home = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  description = "A multilingual blog about travel and experiences in Japan"
  author = "devhou.se"

  # Gallery thumbnail settings
  # Smaller values = more thumbnails across the page
  # Desktop: 200px shows ~2 thumbnails, 130px shows ~3 thumbnails
  # Mobile: 120px is recommended for mobile devices
  galleryThumbnailMinWidth = "120px"
  galleryThumbnailMinWidthMobile = "120px"

[author]
  name = "devhou.se"
  email = "blog@devhou.se"

[services.rss]
  limit = 20  # Number of posts in RSS feed (0 = unlimited)

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"