name: Post Archiver

on:
  issue_comment:

concurrency:
  group: archive-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  post:
    name: Archive post
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check-comment.outputs.valid }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: contains(github.event.issue.labels.*.name, 'post')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check comment
        id: check-comment
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          if [[ "${{ github.event.comment.body }}" == "/archive" ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Python with dependencies
        if: steps.check-comment.outputs.valid == 'true'
        uses: ./.github/actions/setup-python-deps

      - name: Create branch
        if: steps.check-comment.outputs.valid == 'true'
        run: |
          git checkout "archive/${{ github.event.issue.number }}" || git checkout -b "archive/${{ github.event.issue.number }}"

      - name: Archive post
        if: steps.check-comment.outputs.valid == 'true'
        env:
          POST_NUMBER: ${{ github.event.issue.number }}
        run: |
          python python/archiver.py
      - name: Setup git bot
        if: steps.check-comment.outputs.valid == 'true'
        uses: ./.github/actions/setup-git-bot

      - name: Commit post
        if: steps.check-comment.outputs.valid == 'true'
        run: |
          git add site/content/${{ github.event.issue.number }}.md
          git commit -m "Archive post ${{ github.event.issue.number }}"
          git push

      - name: Create and merge PR
        if: steps.check-comment.outputs.valid == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Archive post #${{ github.event.issue.number }}" --body "Archive post ${{ github.event.issue.number }}" --base main --head "archive/${{ github.event.issue.number }}"
          gh pr merge --squash --delete-branch

  update-gallery:
    name: Update Gallery
    uses: ./.github/workflows/gallery.yaml
    needs: post
    if: needs.post.outputs.valid == 'true'
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    needs: update-gallery
    if: needs.post.outputs.valid == 'true'
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  close-issue:
    name: Close issue
    runs-on: ubuntu-latest
    needs: deploy
    if: needs.post.outputs.valid == 'true'
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Close issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close ${{ github.event.issue.number }}
