name: Commenter

on:
  issues:
    types:
      - opened
      - reopened

env:
  MSG_INSTRUCTION: "\"/post\" to publish the blog post"

jobs:
  comment:
    name: Comment instructions
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment on issue
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_COUNT=$(gh issue view ${{ github.event.issue.number }} --json comments -q " .[][] | select(.author.login==\"github-actions\") | .id" | wc -l)
          if [ $COMMENT_COUNT -eq 0 ]; then
            gh issue comment ${{ github.event.issue.number }} -b "$MSG_INSTRUCTION"
          fi
