name: "Update Gallery"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  gallery:
    name: "Update Gallery"
    permissions: write-all
    runs-on: ubuntu-latests
    steps:
    - name: "checkout"
      uses: actions/checkout@v4
      with:
        ref: main
    - name: "setup python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: "install dependencies"
      run: pip install -r python/requirements.txt
    - name: "create branch"
      run: |
       git checkout "post/gallery" || git checkout -b "post/gallery"
    - name: "update image of the day"
      run: |
          python python/dailyimage.py
    - name: "commit post"
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global push.autosetupremote true
        git add site/content/gallery.md
        git add site/themes/devhouse-theme/layouts/partials/gallery.html
        git commit -m "Update gallery" || echo "No changes to commit"
        git push
    - name: "merge branch"
      if: steps.commit-post.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Update gallery" --body "" --base main --head "post/gallery"
        gh pr merge --auto --squash --delete-branch || echo "No changes to merge"

  deploy:
    name: "Deploy"
    uses: ./.github/workflows/deploy.yaml
    if: ${{ !github.event_name == 'workflow_call' }}
    needs: gallery
    secrets: inherit
    permissions: write-all
