name: Update Gallery

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: gallery-update
  cancel-in-progress: false

jobs:
  gallery:
    name: Update Gallery
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Python with dependencies
      uses: ./.github/actions/setup-python-deps

    - name: Create branch
      run: |
       git checkout "post/gallery" || git checkout -b "post/gallery"

    - name: Update image of the day
      run: python python/dailyimage.py

    - name: Setup git bot
      uses: ./.github/actions/setup-git-bot

    - name: Commit changes
      run: |
        git add site/themes/devhouse-theme/layouts/partials/gallery.html site/content/gallery.md
        git commit -m "Update gallery" || echo "No changes to commit"
        git push

    - name: Create and merge PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Update gallery" --body "" --base main --head "post/gallery" || echo "No changes to commit"
        gh pr merge --auto --squash --delete-branch || echo "No changes to merge"
        git push -d origin "post/gallery" || echo "No branch to delete"

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    if: github.event_name != 'workflow_call'
    needs: gallery
    secrets: inherit
