name: Imager

on:
  workflow_call:

jobs:
  imager:
    name: Imager
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Cache Images
        run: |
          go run go/imager/imager.go
