name: Update Imager Cache

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: imager-cache-update
  cancel-in-progress: false

jobs:
  update-cache:
    name: Update Imager Cache
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Setup GCP credentials
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

    - name: Create branch
      run: |
        git checkout -b "update/imager-cache"

    - name: Rebuild cache from GCS
      run: go run go/imager/imager.go --rebuild-cache

    - name: Setup git bot
      uses: ./.github/actions/setup-git-bot

    - name: Commit and push changes
      id: commit
      run: |
        git add imager-cache.txt
        if git diff --cached --quiet; then
          echo "No changes to commit"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Update imager cache"
          git push -u origin update/imager-cache
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create and merge PR
      if: steps.commit.outputs.has_changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Update imager cache" --body "" --base main --head "update/imager-cache"
        gh pr merge --squash --delete-branch
